USE [master]
GO

/****** Object:  Database [testirm]    Script Date: 5/10/2021 11:28:05 AM ******/
DROP DATABASE [testirm]
GO

/****** Object:  Database [testirm]    Script Date: 5/10/2021 11:28:05 AM ******/
CREATE DATABASE [testirm]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'testirm', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\testirm.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'testirm_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\testirm_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [testirm].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [testirm] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [testirm] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [testirm] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [testirm] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [testirm] SET ARITHABORT OFF 
GO

ALTER DATABASE [testirm] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [testirm] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [testirm] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [testirm] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [testirm] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [testirm] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [testirm] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [testirm] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [testirm] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [testirm] SET  DISABLE_BROKER 
GO

ALTER DATABASE [testirm] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [testirm] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [testirm] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [testirm] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [testirm] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [testirm] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [testirm] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [testirm] SET RECOVERY FULL 
GO

ALTER DATABASE [testirm] SET  MULTI_USER 
GO

ALTER DATABASE [testirm] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [testirm] SET DB_CHAINING OFF 
GO

ALTER DATABASE [testirm] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [testirm] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [testirm] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [testirm] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [testirm] SET QUERY_STORE = OFF
GO

ALTER DATABASE [testirm] SET  READ_WRITE 
GO


